GET http://localhost:3333/youtube

###

GET http://localhost:3333/api/metrics

###

GET http://localhost:3333/api/links

###

POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "youtube",
  "url": "https://www.youtube.com"
}